//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnology.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsInProducts
    {
        public int Id { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public int Count { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
