//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechnology.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsPartners
    {
        public int Id { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> IdApplication { get; set; }
        public int CountProducts { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual Products Products { get; set; }
    }
}
